---
title: "cs_behavioral_tempmem_analyses"
author: "Lainey Costa'
output: html_document
date: "2026-09-16"
---

```{r libraries}
#load in packages
library(rio)
library(stringr)
library(dplyr)
library(tidyr)
library(lme4)
library(effsize)
library(emmeans)
library(ggplot2)
library(pbkrtest)
```


```{r data path}
#find data path 
file_path <- file.path('../../experiments/click-and-switch/data/scored_fmri_data')

##only run this once, converts excels to csvs 
#files_excel <- list.files(path = file_path, pattern = "xlsx", full.names = T)
#excel_to_csv <- mapply(convert, files_excel, gsub("xlsx", "csv", files_excel))

csv_path <- list.files(path = file_path, pattern = "\\.csv$", full.names = T)

```

```{r loop}
#loop to pull columns of interest from each csv 
tempmem_allsubs <- c()

for(i in 1:length(csv_path)){
  data <- read.csv(csv_path[i])
  
  data <- data %>%
    select(Subject_ID, Video,Filter_0_instruction_1_task, App_1_BothLecture_2_BothInsta_3_diff,
           SameFrame_0_no_1_yes, SwitchEvent_0_no_1_yes, Exclude_0_no_1_yes, 
           left_event_frame, right_event_frame, 
           correct_answer, TemMem_resp.keys, TemMem_resp.corr,
           TemMem_resp.rt, TimePer_resp.keys, TimePer_resp.rt
           )
  
  tempmem_allsubs <- rbind(tempmem_allsubs, data)
}

```

```{r exclusions}
excluded_ids <- c("CS_fmri_004", "CS_fmri_059", "CS_fmri_096") 

tempmem_allsubs <- tempmem_allsubs %>%
  filter(!Subject_ID %in% excluded_ids)

#now remove all bad trials
tempmem_allsubs <- tempmem_allsubs %>%
  filter(Filter_0_instruction_1_task == 1 & Exclude_0_no_1_yes == 0)
```

```{r temp order memory analyses}
tempmem_allsubs$App_1_BothLecture_2_BothInsta_3_diff <- as.factor(tempmem_allsubs$App_1_BothLecture_2_BothInsta_3_diff)
#tempmem_allsubs$SwitchEvent_0_no_1_yes <- as.factor(tempmem_allsubs$SwitchEvent_0_no_1_yes)


#descriptives (mean, standard deviation)
tempmem_descriptives <- aggregate(tempmem_allsubs, TemMem_resp.corr ~  App_1_BothLecture_2_BothInsta_3_diff + SwitchEvent_0_no_1_yes + Subject_ID, function(x) c(mean = mean(x), sd = sd(x)))
  

#LME: effects of switch category and event continuity 
tempmem_lme <- lmer(data = tempmem_allsubs, TemMem_resp.corr ~ App_1_BothLecture_2_BothInsta_3_diff 
                    * SwitchEvent_0_no_1_yes + (1 | Subject_ID))
summary(tempmem_lme)
anova(tempmem_lme)

#estimated marginal means 
emmeans <- emmeans(tempmem_lme, ~App_1_BothLecture_2_BothInsta_3_diff * SwitchEvent_0_no_1_yes, pbkrtest.limit = 6000)
pairs(emmeans, by = "SwitchEvent_0_no_1_yes")

```

```{r subj time analyses}
#create a subj time bin 
tempmem_allsubs$time_bin = ifelse(tempmem_allsubs$TimePer_resp.keys %in% c(1, 2), 0, 1) # 0 = short, 1 = long

#GLME: switch + event continuity +interaction
subj_glmer <- glmer(data = tempmem_allsubs, family = binomial, time_bin ~ App_1_BothLecture_2_BothInsta_3_diff * SwitchEvent_0_no_1_yes + (1 | Subject_ID))

summary(subj_glmer)
car::Anova(subj_glmer, test = "Chisq")

#estimated marginal means 
emmeans_subj <- emmeans(subj_glmer, ~App_1_BothLecture_2_BothInsta_3_diff * SwitchEvent_0_no_1_yes, type = "response")

#effects of app by switch 
pairs(emmeans_subj, by = "SwitchEvent_0_no_1_yes")

#effects of switch by app
pairs(emmeans_subj, by = "App_1_BothLecture_2_BothInsta_3_diff")

summary(emmeans_subj)
```

```{r temp order plots}
#bar plot
ggplot(tempmem_descriptives, aes(x = as.factor(SwitchEvent_0_no_1_yes), y = TemMem_resp.corr, fill = as.factor(App_1_BothLecture_2_BothInsta_3_diff))) +
  geom_bar(stat = "summary", width = 0.6, position = "dodge") +
  #geom_jitter(width = 0.08, alpha = 0.4, color = "black") +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", position = position_dodge(0.6), width = 0.2) +
  geom_hline(yintercept = 0.5, color = "red", linetype = "dashed", size = 0.3) +
  scale_fill_manual(values = c("blue", "lightgreen","mediumorchid"), name = "Condition", labels = c("Lecture-Lecture", "Insta-Insta", "Lecture-Insta")) +
  xlab("Switch Condition") +
  ylab("Temporal Memory Accuracy") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(color = "black"))

```
```{r}
tempmem_allsubs$TimePer_resp.keys <- as.numeric(tempmem_allsubs$TimePer_resp.keys)

subj_prop <- tempmem_allsubs %>%
    group_by(App_1_BothLecture_2_BothInsta_3_diff, SwitchEvent_0_no_1_yes, TimePer_resp.keys) %>%
    summarise(n = n()) %>%
    mutate(frequency = n/sum(n))

#stack plot
ggplot(subj_prop, aes(x = as.factor(c(App_1_BothLecture_2_BothInsta_3_diff)), y = frequency, fill = as.factor(TimePer_resp.keys))) +
  geom_bar(stat = "identity", position = "stack") +
  facet_grid(SwitchEvent_0_no_1_yes ~ App_1_BothLecture_2_BothInsta_3_diff, labeller = labeller(App_1_BothLecture_2_BothInsta_3_diff = c(
    "1" = "Lecture-Lecture",
    "2" = "Insta-Insta",
    "3" = "Different"), 
    SwitchEvent_0_no_1_yes = c(
      "0" = "Same Event",
      "1" = "Different Events"
    ))) +
  scale_fill_manual(values = c("lightpink", "deeppink","lightgreen", "darkgreen"), name = "Estimate Type", labels = c("Very short", "Short", "Long", "Very Long")) +
  ylab("Percentage") +
  xlab("Switch Condition") +
  scale_x_discrete(labels = NULL) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(color = "black"))


```

