---
title: "deepucontrol_behavioral_prelim_analyses"
author: "Lainey Costa'
output: html_document
date: "2026-09-28"
---

```{r libraries}
#load in packages
library(rio)
library(stringr)
library(dplyr)
library(tidyr)
library(lme4)
library(lmerTest)
library(effsize)
library(emmeans)
library(ggplot2)
library(ggpattern)
library(car)
```


```{r data path}
#find data path 
file_path <- file.path('../../experiments/click-and-switch/data/deepucontrol_behavioral_data')

csv_path <- list.files(path = file_path, pattern = ".*DeepuControl.*\\.csv$", recursive = T, full.names = T)

```

```{r loop}
#loop to pull columns of interest from each csv 
dc_control_allsubs <- c()

for(i in 1:length(csv_path)){
   if(i %in% c(36, 47, 83, 99)){ #remove participant 84, ran as 83; remove 7, 37, and 47 because those IDs aren't in the CS df
     next
     }
  
  data <- read.csv(csv_path[i])

  data <- data %>%
    select(participant, left_event_frame, right_event_frame, video_name,
           correct_answer, TemMem_resp.keys, TemMem_resp.corr,
           TemMem_resp.rt, TimePer_resp.keys, TimePer_resp.rt
           )
  
  data <- na.omit(data)
  
  dc_control_allsubs <- rbind(dc_control_allsubs, data)
}

```

```{r}
#import click and switch data 
cs_og_allsubs <- import("~/workspace/click-and-switch/c+s_beh_tempmem.csv")

#filter c+s data by subj IDs in the control 
cs_og_allsubs <- cs_og_allsubs %>%
  filter(Subject_ID %in% dc_control_allsubs$video_name) %>%
  filter(Filter_0_instruction_1_task == 1) %>%
  distinct(Subject_ID, left_event_frame, right_event_frame, .keep_all =T) %>%
  na.omit()

cs_og_allsubs$participant <- cs_og_allsubs$Subject_ID

```

```{r}
#combine og and control together, and add a column that has "control" vs. "OG" 
cs_og_allsubs <- cs_og_allsubs[-c(1,3,5)]

cs_og_allsubs$TemMem_resp.rt <- as.numeric(cs_og_allsubs$TemMem_resp.rt)

names(dc_control_allsubs)[names(dc_control_allsubs) == 'video_name'] <- 'Subject_ID'

cs_og_allsubs$version <- "OG"

#first, left join the app switch and event switch with the appropriate matches in the deepu control (join by in the order the columns present themselves)
dc_join <- left_join(dc_control_allsubs, select(cs_og_allsubs, left_event_frame, right_event_frame, Subject_ID, App_1_BothLecture_2_BothInsta_3_diff, SwitchEvent_0_no_1_yes, Exclude_0_no_1_yes), by = join_by(left_event_frame, right_event_frame, Subject_ID))

dc_join$version <- "control"

#now join the control and the OG 
dc_join$participant <- as.character(dc_join$participant)
full_combined <- full_join(dc_join, cs_og_allsubs)

```

```{r exclusions}
#excluded_ids <- c("CS_702", "CS_703", "CS_705", "CS_709", "CS_717", "CS_721", "CS_735", "CS_748", "CS_774", "CS_771", "CS_772", "CS_802", "CS_831")


#full_combined <- full_combined %>%
#  filter(!Subject_ID %in% excluded_ids)

#now remove all bad trials
full_combined <- full_combined %>%
  filter(Exclude_0_no_1_yes == 0 & App_1_BothLecture_2_BothInsta_3_diff != 0)
```

```{r temp order memory analyses}
full_combined$App_1_BothLecture_2_BothInsta_3_diff <- as.factor(full_combined$App_1_BothLecture_2_BothInsta_3_diff)
#tempmem_allsubs$SwitchEvent_0_no_1_yes <- as.factor(tempmem_allsubs$SwitchEvent_0_no_1_yes)

#descriptives (mean, standard deviation)
tempmem_descriptives <- aggregate(full_combined, TemMem_resp.corr ~  App_1_BothLecture_2_BothInsta_3_diff + SwitchEvent_0_no_1_yes + version + participant, function(x) c(mean = mean(x), sd = sd(x)))
  

#LME: effects of switch category and event continuity 
tempmem_lme <- glmer(data = full_combined, TemMem_resp.corr ~ App_1_BothLecture_2_BothInsta_3_diff 
                    * SwitchEvent_0_no_1_yes + version + (1 | participant), family = binomial)
summary(tempmem_lme)
Anova(tempmem_lme)
anova(tempmem_lme)

#estimated marginal means 
emmeans <- emmeans(tempmem_lme, ~App_1_BothLecture_2_BothInsta_3_diff * SwitchEvent_0_no_1_yes | version)
emm <- emmeans(tempmem_lme, ~App_1_BothLecture_2_BothInsta_3_diff * SwitchEvent_0_no_1_yes | version, type = "response")

#pivot wider, in case want to check in Jamovi 
tempmem <- tempmem_descriptives %>%
  pivot_wider(values_from = TemMem_resp.corr, names_from = c(App_1_BothLecture_2_BothInsta_3_diff, SwitchEvent_0_no_1_yes, version))
```

```{r subj time analyses}
#create a subj time bin 
full_combined$time_bin = ifelse(full_combined$TimePer_resp.keys %in% c(1, 2), 0, 1) # 0 = short, 1 = long

#GLME: switch + event continuity +interaction
subj_glmer <- glmer(data = full_combined, family = binomial, time_bin ~ App_1_BothLecture_2_BothInsta_3_diff * SwitchEvent_0_no_1_yes + version + (1 | participant))

summary(subj_glmer)
Anova(subj_glmer, test = "Chisq")

#estimated marginal means 
emmeans_subj <- emmeans(subj_glmer, ~App_1_BothLecture_2_BothInsta_3_diff * SwitchEvent_0_no_1_yes, type = "response")

#effects of app by switch 
pairs(emmeans_subj, by = "SwitchEvent_0_no_1_yes")

#effects of switch by app
pairs(emmeans_subj, by = "App_1_BothLecture_2_BothInsta_3_diff")

summary(emmeans_subj)
```

```{r temp order plots}
#bar plot
ggplot(tempmem_descriptives, aes(x = as.factor(SwitchEvent_0_no_1_yes), y = TemMem_resp.corr, fill = as.factor(App_1_BothLecture_2_BothInsta_3_diff), pattern = as.factor(version))) +
  geom_bar_pattern(stat = "summary", width = 0.8, position = "dodge", pattern_color = "black", pattern_fill = "black", pattern_spacing = .02, pattern_size = .1) +
  scale_pattern_manual(values = c('stripe', 'none', 'stripe')) +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", position = position_dodge(0.8), width = 0.2) +
  geom_hline(yintercept = 0.5, color = "red", linetype = "dashed", size = 0.3) +
  scale_fill_manual(values = c("blue", "lightgreen","mediumorchid"), name = "Condition", labels = c("Lecture-Lecture", "Insta-Insta", "Lecture-Insta")) +
  xlab("Switch Condition") +
  ylab("Temporal Memory Accuracy") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(color = "black"))

```

```{r subj time plots}
full_combined$TimePer_resp.keys <- as.numeric(full_combined$TimePer_resp.keys)

subj_prop <- full_combined %>%
    group_by(App_1_BothLecture_2_BothInsta_3_diff, SwitchEvent_0_no_1_yes, version, TimePer_resp.keys) %>%
    summarise(n = n()) %>%
    mutate(frequency = n/sum(n))

#stack plot
ggplot(subj_prop, aes(x = as.factor(c(App_1_BothLecture_2_BothInsta_3_diff)), y = frequency, fill = as.factor(TimePer_resp.keys))) +
  geom_bar(stat = "identity", position = "stack") +
  facet_grid(version ~ SwitchEvent_0_no_1_yes ~ App_1_BothLecture_2_BothInsta_3_diff, labeller = labeller(App_1_BothLecture_2_BothInsta_3_diff = c(
    "1" = "Lecture-Lecture",
    "2" = "Tiktok-Tiktok",
    "3" = "Different"), 
    SwitchEvent_0_no_1_yes = c(
      "0" = "Same Event",
      "1" = "Different Events"
    ))) +
  scale_fill_manual(values = c("lightpink", "deeppink","lightgreen", "darkgreen"), name = "Estimate Type", labels = c("Very short", "Short", "Long", "Very Long")) +
  ylab("Percentage") +
  xlab("Switch Condition") +
  scale_x_discrete(labels = NULL) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(color = "black"))

#bar plots
#x axis: same/diff event, y axis is proportion response, fill is the switch type 
barplot_subj <- aggregate(TimePer_resp.keys ~ App_1_BothLecture_2_BothInsta_3_diff + SwitchEvent_0_no_1_yes + version + participant, data = full_combined, mean)
barplot_subj$prop <- barplot_subj$TimePer_resp.keys/4

ggplot(barplot_subj, aes(x = as.factor(SwitchEvent_0_no_1_yes), y = prop, fill = as.factor(App_1_BothLecture_2_BothInsta_3_diff), pattern = as.factor(version))) +
  geom_bar_pattern(stat = "summary", width = 0.6, position = "dodge", pattern_color = "black", pattern_fill = "black", pattern_spacing = .02) +
  scale_pattern_manual(values = c('stripe', 'none', 'stripe')) +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", position = position_dodge(0.6), width = 0.2) +
  scale_fill_manual(values = c("lightpink", "darkgreen", "lightblue"), name = "Switch Type", labels = c("lecture-lecture", "tiktok-tiktok", "lecture-tiktok")) +
  xlab("Switch Condition") +
  ylab("Proportion Subjective Distance Ratings") +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(color = "black"))


```

